services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ".testdir:/testdir"
    environment:
      GIN_MODE: release
    restart: unless-stopped
