// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.6.1
// source: api/judge.proto

package judge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GithubUrl string `protobuf:"bytes,1,opt,name=github_url,json=githubUrl,proto3" json:"github_url,omitempty"`
}

func (x *SubmissionRequest) Reset() {
	*x = SubmissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_judge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionRequest) ProtoMessage() {}

func (x *SubmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_judge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionRequest.ProtoReflect.Descriptor instead.
func (*SubmissionRequest) Descriptor() ([]byte, []int) {
	return file_api_judge_proto_rawDescGZIP(), []int{0}
}

func (x *SubmissionRequest) GetGithubUrl() string {
	if x != nil {
		return x.GithubUrl
	}
	return ""
}

type SubmissionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Submitted bool `protobuf:"varint,1,opt,name=submitted,proto3" json:"submitted,omitempty"`
}

func (x *SubmissionReply) Reset() {
	*x = SubmissionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_judge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmissionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionReply) ProtoMessage() {}

func (x *SubmissionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_judge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionReply.ProtoReflect.Descriptor instead.
func (*SubmissionReply) Descriptor() ([]byte, []int) {
	return file_api_judge_proto_rawDescGZIP(), []int{1}
}

func (x *SubmissionReply) GetSubmitted() bool {
	if x != nil {
		return x.Submitted
	}
	return false
}

var File_api_judge_proto protoreflect.FileDescriptor

var file_api_judge_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2f, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x22, 0x32, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x55, 0x72, 0x6c, 0x22, 0x2f, 0x0a, 0x0f,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x32, 0x4a, 0x0a,
	0x09, 0x43, 0x6f, 0x64, 0x65, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x4a, 0x75,
	0x64, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x2e,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_judge_proto_rawDescOnce sync.Once
	file_api_judge_proto_rawDescData = file_api_judge_proto_rawDesc
)

func file_api_judge_proto_rawDescGZIP() []byte {
	file_api_judge_proto_rawDescOnce.Do(func() {
		file_api_judge_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_judge_proto_rawDescData)
	})
	return file_api_judge_proto_rawDescData
}

var file_api_judge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_judge_proto_goTypes = []interface{}{
	(*SubmissionRequest)(nil), // 0: judge.SubmissionRequest
	(*SubmissionReply)(nil),   // 1: judge.SubmissionReply
}
var file_api_judge_proto_depIdxs = []int32{
	0, // 0: judge.CodeJudge.JudgeCode:input_type -> judge.SubmissionRequest
	1, // 1: judge.CodeJudge.JudgeCode:output_type -> judge.SubmissionReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_judge_proto_init() }
func file_api_judge_proto_init() {
	if File_api_judge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_judge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_judge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmissionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_judge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_judge_proto_goTypes,
		DependencyIndexes: file_api_judge_proto_depIdxs,
		MessageInfos:      file_api_judge_proto_msgTypes,
	}.Build()
	File_api_judge_proto = out.File
	file_api_judge_proto_rawDesc = nil
	file_api_judge_proto_goTypes = nil
	file_api_judge_proto_depIdxs = nil
}
